language: ruby
rvm:
 - 2.6.3

before_script:
 - chmod +x ./tests/portal-test.sh

script:
 - ./tests/portal-test.sh
 - python -m SimpleHTTPServer 5000
 - STATUSCODE=$(curl -I http://localhost:5000/index.html &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
 - STATUSCODE=$(curl -I http://localhost:5000/portal.html &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 52; then exit 0; fi
 

env:
 global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true        

cache: bundler  
