language: ruby
rvm:
 - 2.6.3

before_script:
 - chmod +x ./tests/portal-test.sh

script:
 - ./tests/portal-test.sh
 - curl -I http://localhost/index.html
 
env:
 global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true        

cache: bundler  
